### ISSUE TITLE
Segmentation Identifiers

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#137]
Hi,

I'm trying to segment a scalar field using the contour tree (FTM).

If I apply a 'RegionType' threshold on the segmentation, I am able to see all regions that I am interested in [1 for Maxima, 3 for Split Saddles].

Here's a screenshot from a Von Karman sheet, segmented on split saddles.

![screen shot 2018-08-07 at 16 10 18](https://user-images.githubusercontent.com/9362064/43781109-71822bbe-9a5c-11e8-9d89-2694c991f483.png)

I'm interested in knowing the segmented region associated with a particular saddle/maxima. 

When I try to threshold further on 'SegmentationId', they seem to be disconnected in nature. For example, look at this screenshot. You should be able to notice three different blue regions on the right. However, this same method seems to work properly when dealing with local maximas.

![screen shot 2018-08-07 at 16 13 35](https://user-images.githubusercontent.com/9362064/43781297-df67b054-9a5c-11e8-8006-fe19418d1e84.png)

Is this behaviour expected? If yes, how should I about looking at regions associated with split saddles?

Cheers!

**Comment by kamakshidasan** [comment]
Also, I'm using the Github version of TTK.

**Comment by julien-tierny** [comment]
hi there,

contour tree driven segmentations are vertex based (if they were to segment 
through faces, they'd be *much* more expenseive to compute).

if your input mesh is not dense enough, pre-images of arcs of the tree may be 
sparsely sampled by the vertices and hence, appear disconnected while they are 
not.

so in short, yes, this is the expected behavior.
I'm going to close this issue then.

I'd recommend to continue this discussion on the ttk-users@googlegroups.com 
mailing list, but in short, refining your input mesh should be a sufficient 
workaround.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
@julien-tierny, Could you please forward this to ttk-users? I can't seem to forward this thread to my e-mail with the above screenshots.

**Comment by julien-tierny** [comment]
already did.
thanks.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
