### ISSUE TITLE
Topological Compression sometimes crashes

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#141]
I tried to play with this plugin by looking at this VTK file. It crashed paraview

[ttkTopologicalCompression] Starting computation on field 'Tiff'...
[ttkTopologicalCompression] Unsupported data type :(
Segmentation fault: 11
[cell.vtk.zip](https://github.com/topology-tool-kit/ttk/files/2410574/cell.vtk.zip)

**Comment by julien-tierny** [comment]
hi,

thanks for your message.

> [ttkTopologicalCompression] Starting computation on field 'Tiff'...
> [ttkTopologicalCompression] Unsupported data type :(
> Segmentation fault: 11
ttkTopologicalCompression only makes sense for floating point data and does not 
support non floating point values (as 'briefly' suggested by the error message).

if you want to see what this module would do on your data, please convert it 
first to floating point data with the Calculator plugin for instance (and use 
your Tiff field in the computation formula field). that will implicitly convert 
your data to doubles. that pipeline works here.

that being said, the module should not crash.

@madblade:
can you have a quick look at this to make sure the module does not crash?

@GuillaumeFavelier:
I tried to use "TTK PointDataConverter" to convert this unsigned char dataset 
to float (or even double) but then "TTK TopologicalCompression" crashes on this 
converted data while it shouldn't (the computation starts and crashes in the 
process). I suspect something wrong in the converter since using the 
calculator instead works.
thanks for having a look into that.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by GuillaumeFavelier** [comment]
Hello,

Yes sure, I'll definitely take a look.

**Comment by julien-tierny** [comment]
hi,

this should be fixed with commit e2f8cc82a74ec32ca58848c9e40516ba4b9b135c

I'm gonna go ahead and close that issue then.

thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
