### ISSUE TITLE
Persistence Diagram not rendered

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#142]
Persistence diagram not shown in Render View, however, Embed in domain works fine.

https://drive.google.com/file/d/1J4WghsnJ8yoRE3Pp78C7_1nHJZrqBDND/view?usp=sharing

**Comment by julien-tierny** [comment]
please provide the data in vti format and be more specific about your pipeline 
(what field did you use, etc)
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
I updated the link above with a vti file

Pipeline:
- Load the file
- Select 'magnitude' as scalar field
- Apply Persistence Diagram

**Comment by julien-tierny** [comment]
hi,

use the "Reset" view button (green cross icon) to reset the planar view based 
on the rendered object. that works here.

the diagram is initially not rendered well because some of the points in your 
data set have value 1e+35 which does not seem to make much sense. 
it looks like your data has not been well imported.

closing this one.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
thanks :)
