### ISSUE TITLE
New ttkAlgorithm API breaks module management scripts

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#351]
The module management scripts (scripts/createTTKmodule.sh) recently switched to the new ttkAlgorithm API for the generation of a new module (based on HelloWorld, commit fdffe9ec7856048b277fdc8f33cafadb7e8ab93c).

However, when building now ttk with the new module (MyNewTestModule), a linking error systematically occurs:
../../lib64/libttkMyNewTestModuleCS.a(ttkMyNewTestModuleClientServer.cxx.o): In function `ttkUtils::GetVoidPointer(vtkDataArray*, long long)':
ttkMyNewTestModuleClientServer.cxx:(.text+0x10): multiple definition of `ttkUtils::GetVoidPointer(vtkDataArray*, long long)'
../../lib64/libttkHelloWorldCS.a(ttkHelloWorldClientServer.cxx.o):ttkHelloWorldClientServer.cxx:(.text+0x10): first defined here

I guess this one is for @JonasLukasczyk  and @CharlesGueunet as both of you guys recently touched the involved parts of ttkUtils.

**Comment by pierre-guillou** [comment]
I can confirm that this bug also happens to me.

I think the problem is caused by the functions in ttkUtils being defined in the header file, instead of being defined in a separate .cpp file.

One quick workaround is to move the ```#include <ttkUtils.h>``` statement from ttkHelloWorld.h to ttkHelloWorld.cpp. This makes the ttkUtils functions only visible to the ttkHelloWorld module and avoids collisions.

**Comment by JonasLukasczyk** [comment]
PR #361 fixes this issue. I guess we can close this issue.

**Comment by julien-tierny** [comment]
alright, thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
