### ISSUE TITLE
ttkAlgorithm should check if FillOutputPortInformation was successful

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk#393]
Currently ttkAlgorithm assumes that each filter that inherits from it correctly specifies its output port information. If there is a programming error however, ParaView will crash with an ambiguous error message. I will open a new PR in which ttkAlgorithm performs some sanity checks to prevent this issue.

**Comment by julien-tierny** [comment]
related to that (more related to the input actually), the new ttkAlgorithm API does not check if the input is a homogeneous simplicial mesh prior to creating a ttk::Triangulation object.

@kappe-c added that feature in recently (see coreve/vtk/ttkTriangulationAlgorithm/ttkTriangulation::setInputData())

we may want to have a similar warning in ttkAlgorithm.

@kappe-c: maybe something to add on your todo list for the hackathon next week?

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
it looks like these checks are really needed because ttkAlgorithm::GetTriangulation() crashes right now in some occasions.

for instance, compute some critical points on something and then call helloworld on them (crash).

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
These checks are now added with PR #405
