### ISSUE TITLE
Periodic conditions are not properly handled by the Morse-Smale complex in 3D

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#671]
**Describe the bug**
When periodic conditions are enabled in 3D, an excessive number of critical points is identified by the Morse-Smale complex, as reported by an email on the ttk-users@googlegroups.com mailing list on October 20, 2021.

**To Reproduce**
1. Load `BuiltInExample2.vti` from `ttk-data`
2. Apply the PeriodicGrid filter
3. Apply the Morse-Smale complex filter (on the field `log(Rho)`)
4. Too many critical points are reported on the boundary.

**Expected behavior**
Fewer critical points are expected, typically, nearly none on the boundary

**Screenshots**
![issueBoundaryPeriodic](https://user-images.githubusercontent.com/3018628/138040154-5c400f4c-4989-4975-b619-c03464a747b7.png)

**System (please complete the following information):**
 - OS: [e.g. iOS] gentoo linux 
 - Compiler [e.g. 22] gcc
 - Installed TTK's optional dependencies 

**Additional context**
Note that:
- PersistenceDiagram produces the right behavior when periodic conditions are enabled
- ManifoldCheck produces the right behavior when periodic conditions are enabled
  - then it is unlikely that the issue is at the `periodicImplicitTriangulation` level (ManifoldCheck spans a good set of traversal features)
  - plus, the periodic conditions were initially developed with a use case dealing with the Morse-Smale complex in 3D
  - then, I suspect this is a regression introduced with the homotopicExpansion type discrete gradient (which was introduced after periodic conditions, if I'm not mistaken)
- The issue does not appear in 2D, so this may be an issue with the edge-triangle traversal in the homotopicExpansion.

**Comment by julien-tierny** [comment]
I confirm the issue was not present in the version 0.9.8.9, which was the first release using periodic conditions and which was using ttk's original discrete gradient (and not the homotopic expansion).

**Comment by julien-tierny** [comment]
I'm re-opnening the issue as it seems that some bugs can still be observed in 3D when triggering the periodic boundaries, but this time, within the domain (see the "curves" of 1-saddles in light blue):
![at_periodicGrid](https://user-images.githubusercontent.com/3018628/142618733-b9274188-d888-4920-8127-0b8d4ceae7d6.png)

left is ScalarFieldCriticalPoints (with periodicity ON), right is the DiscreteGradient (with periodicity ON) on the at.vti data set.
@tbmasood any quick idea here?

**Comment by pierre-guillou** [comment]
I think I know the cause of this issue.
Since DiscreteGradient represents critical points as barycenters of critical simplices, in this case, the additional 1-saddle represent edges located between the top and bottom boundaries. Corresponding barycenters are located in the middle of the domain in the mirror plane between the two boundaries.

**Comment by julien-tierny** [comment]
good catch!

**Comment by julien-tierny** [comment]
that's why the per critical type counts were correct but the locations were different.
thanks, I'll close the issue.

**Comment by JorgeZorrilla** [comment]
Hi,
I actually think that there must be some bug with the ttkPeriodGrid tool. Here I attach a screeshot from a Morse Smale Complex I computed today using the TTK dev branch currently available:
![criticalPointsNow](https://user-images.githubusercontent.com/92568531/142990754-11ba3a10-f2e6-4179-ba4c-9dcc0e3ad839.png)
And here is the same computation(same input and code) but with the TTK dev branch that was realeased when this bug was fixed at first.
![criticalPointsWithoutNoise](https://user-images.githubusercontent.com/92568531/142990917-f7b78fdb-8812-4f97-9370-751629f5449d.png)
Please, ommit the Isosurface that is displayed because the picture was taken from a presentation I had to do. The thing is that I think that the critical points are no well displayed.
I'll check If I can get that previous version of TTK back to check that outputs.
Thanks,
Jorge
