### ISSUE TITLE
MergeTreeDistanceMatrix & MatrixToHeatMap: Size changes in input MultiBlock lead to crash.

### ISSUE THREAD

**Issue by floWetzels** [topology-tool-kit/ttk#835]
**Describe the bug**
When a MergeTreeDistanceMatrix filter is applied to a multiblock of merge trees and a MatrixToHeatMap filter to the output table, after changing the number of blocks in the pipeline before the MergeTreeDistanceMatrix filter the following happens: paraview crashes with the the console warning "[MatrixToHeatMap] [WARNING] Distance matrix is not square".

**To Reproduce**
1. Open a pipeline as shown in the screenshot.
2. After executing the full pipeline, change the number of blocks in the ExtractBlocks filter.
4. See error message in console.

**Screenshots**
![Screenshot from 2022-09-30 13-55-35](https://user-images.githubusercontent.com/36967183/193264806-b222a5e7-f03f-4e31-82f3-4d92ca420f0c.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Compiler: gcc 9.4.0
 - Paraview version: 5.10.1

**Comment by MatPont** [comment]
Thanks Florian for opening this issue.

I'm able to reproduce the bug. The origin of the problem is due to the table columns selector of Paraview (in `TTKMatrixToHeatMap`). 

If you first execute `TTKMatrixToHeatMap` by manually selecting the columns in the table, then you reduce the input size (like you suggested with `ExtractBlocks` for example) some columns that are not present anymore will still be selected by `TTKMatrixToHeatMap` and the filter will try to access these arrays (whereas they are not anymore in the table) therefore causing a segfault.

A practical solution is to use the "Select Fields with a Regexp" option of `TTKMatrixToHeatMap` and use the following regexp: `Tree[0-9]+` to automatically select the columns of the distance matrix, it will works even if the size change.

However, I will open a PR soon to fix `TTKMatrixToHeatMap` in order to not cause a crash and still working even if the regexp option is not used and the input size change.
