### ISSUE TITLE
Automatic nightly testing on different OS

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#94]
Hi, 

I think this project should have a continuous integration process running the differents .pvsm under different OS. 

Many .pvsm examples seem broken.

**Comment by julien-tierny** [comment]
hi jonathan,

thanks for your feedback.

> I think this project should have a continuous integration process running the differents .pvsm under different OS. 
absolutely, this is something that's on our todo-list.

for the moment, we're using travis-ci which is well integrated to github and which provides certain continuous integration features in their free plans. it seems to be a default continuous integration platform for open-source projects similar in size to ttk.

however, last time I checked, free plans on travis-ci are subject to a time limit for post-commit checks and we are already close to it (currently, the build of paraview plugins is not checked by travis-ci because of this).
also, travis-ci does not seem to provide windows virtual machines in their free plans which currently prevents us from running automatic checks on windows upon code commits.

this is unfortunate. 
suggestions to improve this are welcome.

> Many .pvsm examples seem broken.
ttk contributors mostly run linux systems. 
I make sure that each pvsm example runs fine under linux prior to packaging a release. 
tests on windows are more difficult right now because I don't have access to a native system and ParaView's OpenGL2 features are not supported by most virtual machines.

we're planning on writing an automatic pvsm state checker.
hopefully, we should get started on this in a few weeks from now and we'll make sure it runs fine under windows.

however, given the travis-ci limitations I mentioned above, even if we were to have an automatic pvsm state checker, we currently don't have a solution for its automatic execution upon code commits on github. again, suggestions would be appreciated :)

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by jobordu** [comment]
Hi Julien,

We will take a look at the tests, I must say I am quite happy of this
development.

For the build tool, we (and kitware too) are using BuildBot.

It is self-hosted, there is no cloud solution for that. However, this is an
excellent solution because it fully relies on Python to do all the work.
Moreover, the dashboard of buildbot is quite complete.

Best regards,

Jonathan

**Comment by julien-tierny** [comment]
dear jonathan,

we have now setup an in-house nightly check script (to be used with crontab or 
such) that builds the latest version of the code and runs the demo examples 
automatically on a nightly basis. 
for more details, see https://github.com/topology-tool-kit/ttk-data/blob/
master/tests/nightly.sh

I believe this is going to be a solution which is good enough for now.
if you don't mind I'll go ahead and close this issue. 
please feel free to re-open it if necessary.

we'll address your other issues asap.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
