### ISSUE TITLE
Various bugs with the merge tree states

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#966]
**Describe the bug**
Most of the merge tree states are affected by several bugs.

**To Reproduce**
In the ttk-data repository:
`paraview states/mergeTreeClustering.pvsm`
`paraview states/mergeTreeFeatureTracking.pvsm`
`paraview states/mergeTreePGA.pvsm`
`paraview states/mergeTreeTemporalReduction.pvsm`

**Expected behavior**
The planar layout of the trees includes spheres and tubes. The dimension reductions display properly, see the reference screenshots:
https://topology-tool-kit.github.io/img/gallery/mergeTreeClustering.jpg
https://topology-tool-kit.github.io/img/gallery/mergeTreeFeatureTracking.jpg
https://topology-tool-kit.github.io/img/gallery/mergeTreePGA.jpg
https://topology-tool-kit.github.io/img/gallery/mergeTreeTemporalReduction.jpg

**Screenshots**
Please find below screenshots which exemplify the issues on my system

*Merge tree clustering*
In the planar view of the trees:
- Spheres are missing for the nodes
- The tubes are not colored properly
![Screenshot_20230831_094350](https://github.com/topology-tool-kit/ttk/assets/3018628/6c2ca20d-e7cf-4f00-8777-3d3eca358e8f)

*Merge tree feature tracking*
In the planar view of the trees:
- Spheres are missing for the nodes
- The tubes are not colored properly
![Screenshot_20230831_095908](https://github.com/topology-tool-kit/ttk/assets/3018628/8cf88542-96be-418c-a64c-d02a3dd6c70d)

*Merge tree PGA*
The 2D views are empty :(
(TTKMergeBlockTables2 is empty but ExtractSurface1 does contain the surface???!!!)
![Screenshot_20230831_101530](https://github.com/topology-tool-kit/ttk/assets/3018628/23625129-3ff9-4987-a852-6cfbb0d1cdcf)

*Merge tree temporal reduction*
In the planar view of the trees:
- Spheres are missing for the nodes
- The tubes are not colored properly
![Screenshot_20230831_100824](https://github.com/topology-tool-kit/ttk/assets/3018628/fd2ab5ed-1fb2-4e22-a004-d70442d8519f)

**System (please complete the following information):**
- TTK dev
- ParaView 5.11
- numpy 1.25.2
- scikit-learn 1.1.2

**Additional context**
This bug is for @MatPont (after he's done with his manuscript write-up).

The color bug seems to be a consequence of one of Mathieu's latest PRs regarding the insertion of additional information along the arcs of the merge trees. Maybe it can be fixed in the state itself, but more likely with code adjustments.

The sphere, tubes and surface bugs are a little more surprising (these states are not tested by the CI because of their memory footprint). These should be fixable by state adjustments. Otherwise, one would need to roll back the history of commit to the last version of TTK for which these states were OK and search for the fault commits.

**Comment by julien-tierny** [comment]
Interestingly, these bugs do not seem to affect the PD-PGA state (https://github.com/topology-tool-kit/ttk-data/pull/148).
Maybe the latest re-factoring could be the issue? (https://github.com/topology-tool-kit/ttk/pull/944)

**Comment by MatPont** [comment]
Also interestingly, the states work fine on my computer with the current branches of ttk and ttk-data (except for the color bug in branches). However the libraries version differ.
Perhaps we would need to test these states on other computers (or different libraries version).

**System**
TTK dev
ParaView 5.10
Numpy 1.21.5
scikit-learn 0.23.2 (I'm not sure if we have checked the same thing here since it seems to be a big difference, I printed `sklearn.__version__` after importing sklearn in python).

![Screenshot from 2023-08-31 11-05-53](https://github.com/topology-tool-kit/ttk/assets/34889480/47e72dfd-1067-42b9-885b-94361d96001d)
![Screenshot from 2023-08-31 11-06-31](https://github.com/topology-tool-kit/ttk/assets/34889480/3d5b370b-c965-45e0-9d9b-02134ea138f6)
![Screenshot from 2023-08-31 11-11-09](https://github.com/topology-tool-kit/ttk/assets/34889480/acb589f7-6ba7-48d1-a2c9-3cefcbd8ae61)
![Screenshot from 2023-08-31 11-05-50](https://github.com/topology-tool-kit/ttk/assets/34889480/bdd4649d-938b-4bd9-930a-50793cc3f667)

**Comment by MatPont** [comment]
Same screenshots after updating numpy to 1.25.2.
(It was just a quick attempt to reproduce the bug but I will investigate that, like you said, after the manuscript)

**Comment by julien-tierny** [comment]
I confirm that the issue with the missing geometry can no longer be reproduced (for mergeTreeClustering, mergeTreeTemporalReduction, mergeTreeFeatureTracking, mergeTreePGA).
It looks like this was a numpy related-issue.

**Comment by julien-tierny** [comment]
I confirm the issue is completely solved with PR #974 (tested on my home workstation).
